# Dockerfile-flask
# We simply inherit the Python 3 image. This image does
# not particularly care what OS runs underneath
FROM python:3
# Set an environment variable with the directory
# where we'll be running the app
# Create the directory and instruct Docker to operate
# from there from now on
RUN pwd
RUN mkdir /app
WORKDIR /app
# Expose the port uWSGI will listen on
EXPOSE 5000
# Copy the requirements file in order to install
# Python dependencies
COPY requirements.txt .
# Install Python dependencies
RUN pip install -r requirements.txt
# We copy the rest of the codebase into the image
COPY . .
RUN ls | echo
ENV APP_SETTINGS config.DevelopmentConfig
ENV DATABASE_URL postgresql://postgres:testapp@postgres:5432/app
# Finally, we run uWSGI with the ini file we
# created earlier
CMD ["sh", "backend/start.sh"]
