# docker-compose.yml
version: '3'
services:
  redis:
    image: redis:3.2-alpine
  flask:
    image: flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - 5000:5000
    links:
      - redis
    depends_on:
      - redis
      
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    depends_on:
      - flask
  postgres:
    restart: always    
    image: postgres:10    
    environment:      
        - POSTGRES_USER=postgres      
        - POSTGRES_PASSWORD=testapp      
        - POSTGRES_DB=app   
    volumes:      
        - ./postgres-data/postgres:/data    
    ports:      
        - "5432:5432"  